### PR TITLE
queued softcut crossfades

### PR DESCRIPTION
**Pull request by ranch-verdin**
first commit in this changeset was necessary to make this compile on my machine

### CODE REVIEW

**Comment by ranch-verdin** [comment]
pretty sure I managed to figure out how softcut manages crossfade states, then a queue of length 1 is just a global variable.  So second commit in this diff is an untested 'queued cut' feature.

**Comment by ranch-verdin** [comment]
found the supercollider testbenches lying around, hacked the code, made queued crossfades actually work, woohoo!

**Comment by ranch-verdin** [comment]
Just checked over my change, think I stand by the overall logic. In case it's not immediately obvious the strategy behind this change:

* Simplest way to make the enqueue/dequeue behaviour work for deferred xfades is to make *all* xfades use enqueue/dequeue.

* If you want to initiate an xfade, you have to enqueue it and rely on the frame by frame methods to scoop up the dequeue task when current xfade is done. Obviously, if no xfade in progress, the dequeue happens immediately after enqueue (or maybe one audio frame later).

* I don't know how to profile this change for any potential performance degradation!

As for testing, I fired up crone on laptop, filled a buffer with my voice counting 1 to 10, set fade length to 2s, queued up 2 fades very quickly and observed an immediate fade followed by the deferred fade. Used cout << with 1024 sample Jack buffers to verify when enqueue/dequeue functions are being called.

**Comment by catfact** [comment]
ugh, sorry for going AWOL for a while there. seems good to me

**Pull request merged**
